### ISSUE TITLE
Translation to Chinese

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ejwa/gitinspector#11]
```
Translation of gitinspector to Chinese.
```

Original issue reported on code.google.com by `gitinspe...@ejwa.se` on 21 Jul 2013 at 1:07

**Comment by adam-waldenberg** [comment]
Hi. A new messages.pot has been added with commit 47b11ad, so an update is needed to the translation file. Refer to the commit diff to see all changes.

Once updated, the translation can be included in the upcoming 0.4.2 release.

**Comment by ZhijieWang** [comment]
See attachment. Sorry, I was very busy with exams. Git does not allow any file format other than pictures. So the file is pated below.

# Copyright © 2012-2015 Ejwa Software. All rights reserved.
#
# This file is part of gitinspector.
#
# gitinspector is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# gitinspector is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with gitinspector. If not, see <http://www.gnu.org/licenses/>.
#
# This file was generated with the following command:
#
# Bill Wang <wangzhijiebill@gmail.com>, 2015-2016

msgid ""
msgstr ""
"Project-Id-Version: gitinspector 0.4.2dev\n"
"Report-Msgid-Bugs-To: gitinspector@ejwa.se\n"
"POT-Creation-Date: 2015-10-02 03:35+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: Adam Waldenberg <adam.waldenberg@ejwa.se>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#, python-format
msgid "% in comments"
msgstr "% 的注释"

#, python-format
msgid "% of changes"
msgstr "% 的修改"

msgid "(extensions used during statistical analysis are marked)"
msgstr "（统计分析过程中使用的插件已标记）"

msgid "Age"
msgstr "年龄"

msgid "Author"
msgstr "作者"

msgid "Below are the number of rows from each author that have survived and are still intact in the current revision"
msgstr "下面是过于每位作者在现在的版本了存留下来的行数"

#, python-brace-format
msgid "Checking how many rows belong to each author (Progress): {0:.0f}%"
msgstr "检查每位作者贡献了多少行 (进度): {0:.0f}"

msgid "Commits"
msgstr "提交"

msgid ""
"Copyright © 2012-2014 Ejwa Software. All rights reserved.\n"
"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.\n"
"This is free software: you are free to change and redistribute it.\n"
"There is NO WARRANTY, to the extent permitted by law.\n"
"\n"
"Written by Adam Waldenberg."
msgstr ""
"版权所有 © 2012-2014 Ejwa Software. 保留所有权利。\n"
"GPLv3的许可证+：GNU GPL版本3或更高版本<http://gnu.org/licenses/gpl.html>。\n"
"这是自由软件：您可以自由地更改并重新发布它。\n"
"在法律允许的范围内,没有 任何 保证。\n"
"\n"
"撰写： Adam Waldenberg.\n"
"翻译： 王之杰 （Bill Wang）"

msgid "Deletions"
msgstr "删除"

#, python-format
msgid "Error processing git repository at \"%s\"."
msgstr "在处理\"%s\"库时出现问题"

msgid "HTML output not yet supported in"
msgstr "HTML文本输出暂不支持"

msgid "Hide minor authors"
msgstr "隐藏次要作者"

msgid "Hide rows with minor work"
msgstr "隐藏次要工作"

msgid "Insertions"
msgstr "添加"

msgid "Minor Authors"
msgstr "次要作者"

msgid "Modified Rows:"
msgstr "修改过的行"

msgid "No commited files with the specified extensions were found"
msgstr "未找到符合条件的已提交文件"

msgid "No metrics violations were found in the repository"
msgstr "未在数据库中发现违反指标"

#, python-brace-format
msgid "Repository statistics for {0}"
msgstr "关于{0}代码库统计数据"

msgid "Rows"
msgstr "行数"

msgid "Show minor authors"
msgstr "显示次要作者"

msgid "Show rows with minor work"
msgstr "显示次要行"

msgid "Stability"
msgstr "稳定性"

#, python-brace-format
msgid "Statistical information for the repository '{0}' was gathered on {1}."
msgstr "关于{0}的统计数据基于{1}上信息"

msgid "Text output not yet supported in"
msgstr "文本输出暂不支持"

msgid "The authors with the following emails were excluded from the statistics due to the specified exclusion patterns"
msgstr "下列邮箱相关联的作者已经从数据统计中移除"

msgid "The extensions below were found in the repository history"
msgstr "在资料库中扎到下列插件"

msgid "The following authors were excluded from the statistics due to the specified exclusion patterns"
msgstr "下列作者已按规则从数据统计中移除"

msgid "The following commit revisions were excluded from the statistics due to the specified exclusion patterns"
msgstr "下列提交已按规则从数据统计中移除"

msgid "The following files are suspiciously big (in order of severity)"
msgstr "下列文件过大文件有些可疑 (按可疑性排列)"

msgid "The following files have an elevated cyclomatic complexity (in order of severity)"
msgstr "下列文件过度循环性问题，按问题严重性排列"

msgid "The following files have an elevated cyclomatic complexity density (in order of severity)"
msgstr "下列文件过度循环性密集度问题，按问题严重性排列"

msgid "The following files were excluded from the statistics due to the specified exclusion patterns"
msgstr "下列文件已按排除规律移除数据统计"

msgid "The following historical commit information, by author, was found in the repository"
msgstr "在资料库中找到下列提交记录，已按作者分类"

msgid "The following history timeline has been gathered from the repository"
msgstr "在数据库中收集到下列时间轴"

msgid "The following repsonsibilties, by author, were found in the current revision of the repository (comments are exluded from the line count, if possible)"
msgstr "在最新的资料库修改中，找到下列分工，按作者分类。 （在计算代码数量时尽可能的排除了批注）"

msgid "The given option argument is not a valid boolean."
msgstr "给予的选项不是一个有效的 布尔值 （boolean）"

#, python-brace-format
msgid "The output has been generated by {0} {1}. The statistical analysis tool for git repositories."
msgstr "导出结果已基于{0}{1}生成。Git数据统计软件。"

#, python-brace-format
msgid "Try `{0} --help' for more information."
msgstr "尝试 `{0} --help' 已获得更多信息"

msgid "Unable to determine absolute path of git repository."
msgstr "无法确定git库的绝对路径"

#, python-brace-format
msgid ""
"Usage: {0} [OPTION]... [REPOSITORY]\n"
"List information about the repository in REPOSITORY. If no repository is\n"
"specified, the current directory is used. If multiple repositories are\n"
"given, information will be fetched from the last repository specified.\n"
"\n"
"Mandatory arguments to long options are mandatory for short options too.\n"
"Boolean arguments can only be given to long options.\n"
"  -f, --file-types=EXTENSIONS    a comma separated list of file extensions to\n"
"                                   include when computing statistics. The\n"
"                                   default extensions used are:\n"
"                                   {1}\n"
"  -F, --format=FORMAT            define in which format output should be\n"
"                                   generated; the default format is 'text' and\n"
"                                   the available formats are:\n"
"                                   {2}\n"
"      --grading[=BOOL]           show statistics and information in a way that\n"
"                                   is formatted for grading of student\n"
"                                   projects; this is the same as supplying the\n"
"                                   options -HlmrTw\n"
"  -H, --hard[=BOOL]              track rows and look for duplicates harder;\n"
"                                   this can be quite slow with big repositories\n"
"  -l, --list-file-types[=BOOL]   list all the file extensions available in the\n"
"                                   current branch of the repository\n"
"  -L, --localize-output[=BOOL]   localize the generated output to the selected\n"
"                                   system language if a translation is\n"
"                                   available\n"
"  -m  --metrics[=BOOL]           include checks for certain metrics during the\n"
"                                   analysis of commits\n"
"  -r  --responsibilities[=BOOL]  show which files the different authors seem\n"
"                                   most responsible for\n"
"      --since=DATE               only show statistics for commits more recent\n"
"                                   than a specific date\n"
"  -T, --timeline[=BOOL]          show commit timeline, including author names\n"
"      --until=DATE               only show statistics for commits older than a\n"
"                                   specific date\n"
"  -w, --weeks[=BOOL]             show all statistical information in weeks\n"
"                                   instead of in months\n"
"  -x, --exclude=PATTERN          an exclusion pattern describing the file\n"
"                                   paths, revisions, revisions with certain\n"
"                                   commit messages, author names or author\n"
"                                   emails that should be excluded from the\n"
"                                   statistics; can be specified multiple times\n"
"  -h, --help                     display this help and exit\n"
"      --version                  output version information and exit\n"
"\n"
"gitinspector will filter statistics to only include commits that modify,\n"
"add or remove one of the specified extensions, see -f or --file-types for\n"
"more information.\n"
"\n"
"gitinspector requires that the git executable is available in your PATH.\n"
"Report gitinspector bugs to gitinspector@ejwa.se."
msgstr ""
"用法：{0} [选项]... [目录] \n"
"在目录列出有关库的信息,如果没有指定目录，那么将使用现目录。如果有多个目录，\n"
"将采用指定的最后一个目录\n"
"\n"
"长选项的强制性参数对短选项也适用\n"
"布尔参数只能给予长选项\n"
"  -f, --file-types=EXTENSIONS    一串逗号分隔的文件类型\n"
"                                   这些文件将会被用于计算统计数据.\n"
"                                   默认文件类型:\n"
"                                   {1}\n"
"  -F, --format=FORMAT            指定生成的输出文件的格式；\n"
"                                   默认格式是'text' 和\n"
"                                   可选格式:\n"
"                                   {2}\n"
"      --grading[=BOOL]           按照学生成评判项目的格式，\n"
"                                   显示统计数据和信息；\n"
"                                   等同于 -HlmrTw 选项\n"
"  -H, --hard[=BOOL]              记录行数并且寻找重复的内容;\n"
"                                   如果数据库较大，这个可能会需要一些时间\n"
"  -l, --list-file-types[=BOOL]   列出所有现在的数据库分支的文件格式\n"
"  -L, --localize-output[=BOOL]   在翻译版本存在的前提下，将输出结果翻译到系统语言\n"
"  -m  --metrics[=BOOL]           在分析提交时，检查特定指标\n"
"  -r  --responsibilities[=BOOL]  显示每位作者主要职责\n"
"      --since=DATE               只显示从特定时间起的结果\n"
"  -T, --timeline[=BOOL]          显示提交时间轴, 包括作者名称\n"
"      --until=DATE               只显示特定时间前的结果\n"
"  -w, --weeks[=BOOL]             按周来显示统计数据，而非月\n"
"  -x, --exclude=PATTERN          按特定格式排除不应该被统计\n"
"                                   的文件，作者名字或邮箱;可以按文件名，作者名，作者邮箱,提交信息，路径和版本。可以重复\n"
"  -h, --help                     显示这个帮助信息并退出\n"
"      --version                  显示版本信息并退出\n"
"\n"
"gitinspector 会过滤信息并且仅统计那些修改，增加或减少，指定文件类型的提交，\n"
"如需详细信息，请参考 -f 或 --file-types 选项\n"
"\n"
"gitinspector 需要 git 可运行文件 在 PATH 中.\n"
"错误报告，请寄 gitinspector@ejwa.se."
"翻译错误，请寄 wangzhijiebill@gmail.com"

msgid "WARNING: The terminal encoding is not correctly configured. gitinspector might malfunction. The encoding can be configured with the environment variable 'PYTHONIOENCODING'."
msgstr "警告：命令指示符编码格式有误。gitinspector可能出错。编码格式可以在环境变量的'PYTHONIOENCODING'下修改"

msgid "XML output not yet supported in"
msgstr "XML文本输出暂不支持"

#, python-brace-format
msgid "gitinspector requires at least Python 2.6 to run (version {0} was found)."
msgstr "gitinspector 要求 Python版本至少2.6 去运行 (已找到版本 {0}) "

msgid "invalid regular expression specified"
msgstr "无效的正则表达式"

msgid "is mostly responsible for"
msgstr "主要分工是"

msgid "specified output format not supported."
msgstr "不支持设定的输出文件格式"

#, python-brace-format
msgid "{0} ({1:.3f} in cyclomatic complexity density)"
msgstr "{0} (循环型结构密集度{1: 3f})"

#, python-brace-format
msgid "{0} ({1} estimated lines of code)"
msgstr "{0}（估测代码行数{1}）"

#, python-brace-format
msgid "{0} ({1} in cyclomatic complexity)"
msgstr "{0}（代码循环性结构{1}）"

**Comment by adam-waldenberg** [comment]
Hi. No worries.

You need to go through the translation and reference the latest pot file. This  .po file is using old strings from a previous .pot file. For example

```
msgid ""
"Copyright © 2012-2014 Ejwa Software. All rights reserved.\n"
"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.\n"
"This is free software: you are free to change and redistribute it.\n"
"There is NO WARRANTY, to the extent permitted by law.\n"
"\n"
"Written by Adam Waldenberg."
```

is from an older file (including the translation), so is the following section;

```
#, python-brace-format
msgid ""
"Usage: {0} [OPTION]... [REPOSITORY]\n"
"List information about the repository in REPOSITORY. If no repository is\n"
"specified, the current directory is used. If multiple repositories are\n"
"given, information will be fetched from the last repository specified.\n"
"\n"
"Mandatory arguments to long options are mandatory for short options too.\n"
"Boolean arguments can only be given to long options.\n"
"  -f, --file-types=EXTENSIONS    a comma separated list of file extensions to\n"
"                                   include when computing statistics. The\n"
"                                   default extensions used are:\n"
"                                   {1}\n"
"  -F, --format=FORMAT            define in which format output should be\n"
"                                   generated; the default format is 'text' and\n"
"                                   the available formats are:\n"
"                                   {2}\n"
"      --grading[=BOOL]           show statistics and information in a way that\n"
"                                   is formatted for grading of student\n"
"                                   projects; this is the same as supplying the\n"
"                                   options -HlmrTw\n"
"  -H, --hard[=BOOL]              track rows and look for duplicates harder;\n"
"                                   this can be quite slow with big repositories\n"
"  -l, --list-file-types[=BOOL]   list all the file extensions available in the\n"
"                                   current branch of the repository\n"
"  -L, --localize-output[=BOOL]   localize the generated output to the selected\n"
"                                   system language if a translation is\n"
"                                   available\n"
"  -m  --metrics[=BOOL]           include checks for certain metrics during the\n"
"                                   analysis of commits\n"
"  -r  --responsibilities[=BOOL]  show which files the different authors seem\n"
"                                   most responsible for\n"
"      --since=DATE               only show statistics for commits more recent\n"
"                                   than a specific date\n"
"  -T, --timeline[=BOOL]          show commit timeline, including author names\n"
"      --until=DATE               only show statistics for commits older than a\n"
"                                   specific date\n"
"  -w, --weeks[=BOOL]             show all statistical information in weeks\n"
"                                   instead of in months\n"
"  -x, --exclude=PATTERN          an exclusion pattern describing the file\n"
"                                   paths, revisions, revisions with certain\n"
"                                   commit messages, author names or author\n"
"                                   emails that should be excluded from the\n"
"                                   statistics; can be specified multiple times\n"
"  -h, --help                     display this help and exit\n"
"      --version                  output version information and exit\n"
"\n"
"gitinspector will filter statistics to only include commits that modify,\n"
"add or remove one of the specified extensions, see -f or --file-types for\n"
"more information.\n"
"\n"
"gitinspector requires that the git executable is available in your PATH.\n"
"Report gitinspector bugs to gitinspector@ejwa.se."
```

**Comment by adam-waldenberg** [comment]
Btw. The preferable way to pasting the translation here is to just create a new pull request.

**Comment by ZhijieWang** [comment]
As I was combing through lie by line, I realized there are typos.

`msgid "The following repsonsibilties, by author, were found in the current revision of the repository (comments are exluded from the line count, if possible)"`

responsibilties -- > responsibilities

exlude -> exclude

**Comment by adam-waldenberg** [comment]
Good catch. Create a pull request for anything you find and we can squash those typos.

**Comment by ZhijieWang** [comment]
#80 PR has been created. Please review
