### ISSUE TITLE
what does the format date look like in --Since 

### ISSUE THREAD

**Issue by pacific0437** [ejwa/gitinspector#112]
Can you give some examples about options, not only for Since.
Not everyone is good at ternimal or Linux command or other things.
The document makes me mad.
I have tried --Since=23/4/2016  --Since=2016-4-23  --Since=4/23/2016 --Since=[2016-4-23] --Since=[4/23/2016].

**Comment by pacific0437** [comment]
I also want to exclude all files in 'shared'
Is it right to type it as 
-x ~/Documents/workspace/myproject/shared/**/
or 
-x ~/Documents/workspace/myproject/shared/**/*.js
or
-x ~/Documents/workspace/myproject/shared/**/*.*
or 
-x ~/Documents/workspace/myproject/shared/*

**Comment by adam-waldenberg** [comment]
Hi.

The format of --since is in approxidate (as stated in the wiki). Approxidate is a standard that supports a myriad of formats, including textual strings like "1 month" or "3 years". Strings such as "yyyy-mm-dd" should also work fine. 

The exclusion (-x) string does not need wildcard matching, this is implied by the option (as described in the wiki), unless you use regular expressions.

If you want any of the command line options above to work you also need to encapsulate them inside quotes ( " ).

To exclude all files under shared/ you simply specify;

`-x "shared/"`

Again, If you need more control, the option also supports regexp.
Something like;

` -x "shared/\s+.js" `

or similar could work.

**Comment by pacific0437** [comment]
Got it, thank you.
