### ISSUE TITLE
commit count incosistent with github one

### ISSUE THREAD

**Issue by typekpb** [ejwa/gitinspector#182]
I've noticed, commit count in gitinspector doesn't reflect the reality => too low.

Steps to reproduce:
Run gitspector on this project:
github stats:
![image](https://user-images.githubusercontent.com/499820/42118649-24bbb22a-7c05-11e8-850e-d5558e8d14af.png)

gitinspector stats:
![image](https://user-images.githubusercontent.com/499820/42118665-3dc171d8-7c05-11e8-9a54-4cf7ed0d9471.png)

it seems:
* github counted adam-waldenberg having 411 commits
* gitinspector shows only: 337 commits

Where is the difference gone?

**Comment by typekpb** [comment]
btw. the following opts have been used during the test run:`-mrTw`

**Comment by adam-waldenberg** [comment]
Hi @typekpb. This is the correct behavior. As stated by the documentation, gitinspector only counts commits that include any of the filetypes currently being scanned. Everything else is filtered out. This includes all statistics gitinspector shows you, not only the commit count.

Take, @bartvanandel as an example. He has 6 commits in the repo (not 5 as claimed by GitHub), but only one of them actually consists of any code; https://github.com/ejwa/gitinspector/commit/3d11cdce44711d5f0af56d058689706a2e4ed579

Also notice that gitinspector only counts the 29 insertions from that filetype. Because from all the files @bartvanandel has commited it is only tracking the javascript ones.

So in gitinspectors eyes (with the default filetypes), he only has one valid commit and 29 valid lines/insertions.

If you want to track text files and everything else - please refer to the documentation and FAQ. It should help you with most questions.

Closing this issue.

**Comment by typekpb** [comment]
@adam-waldenberg thank you for clarificatoin, `-f "**"` did the trick for me
