### ISSUE TITLE
How to use --since

### ISSUE THREAD

**Issue by steevanb** [ejwa/gitinspector#185]
Hi,

This is not really an issue.

I'm looking for date format used by `--since` and `--until`. Documentation said `the same as the format used in git itself`, but i've trid some git date formats, no one seems to work.

Could you please update documentation with an example, or write an example here?

**Comment by adam-waldenberg** [comment]
Hi @steevanb The format is called Approxidate (already mentioned by the documentation). What it supports and not gets continuously updated. You can specify everything from strings to linux timestamps. Supplying some kind of complete documentation isn't really possible, as it is a floating implementation. Gitinspector simply calls since/until when it executes git exactly the way you specify it.

you can do for example `gitinspectory.py --since="yesterday"` or `gitinspector.py --since="3 weeks"` or `gitinspectory.py --since="1/1/2010"`.

**Comment by steevanb** [comment]
Thanks!
