### ISSUE TITLE
[0.5.0dev] report lost some author

### ISSUE THREAD

**Issue by jeffery9** [ejwa/gitinspector#193]
as title
run command `gitinspector  -F html -w -T -r -L` lost some author in report.

**Comment by isbkch** [comment]
I got the same here, some authors are not picked up

**Comment by adam-waldenberg** [comment]
Hi. First - this does not help. You need to provide more information. What are you scanning ? What files did these authors actually commit? Before opening issues like these, please read the documentation on how gitinspector actually works. Authors are only shown if they actually commit one of the extensions specified, otherwise they are filtered out.

**Comment by adam-waldenberg** [comment]
Seeing as this is most probably a result of a lack of understanding of how gitinspector actually works I'm closing this issue.
