### ISSUE TITLE
Co-authorship not supported

### ISSUE THREAD

**Issue by raoulkent** [ejwa/gitinspector#209]
# Problem statement
For courses where students are pair programming, this may not be reflected by the commits. As full authorship will go to the author of the commit.

# Proposed solution
[Co-authorship is supported on Github](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-github), and would do well to be integrated into gitinspector.
Supporting this feature could enhance the accuracy of student participation through supporting cooperative programming instead of dissuading cooperation.
Analyzing commit messages and matching `Co-authored-by:` with authors could make for fairer grading.

**Comment by adam-waldenberg** [comment]
Discussed earlier. The Co-authored-by feature in on GitHub is garbage and does not allow you track the history properly. I have concluded it's not possible to implement. Because commands such as `git blame` (and other commands) etc are not aware of this feature. If we just parse it on the gitinspector side the analysis will not be correct.

With that said, If you can implement it with all the analysis features of git intact  - pull requests are welcome. I doubt it's possible though.

The proper solution here is to commit with a "co-author". It's the only way to guarantee that git will actually track the authors and rows correctly.

**Comment by raoulkent** [comment]
I see what you mean.

> The proper solution here is to commit with a "co-author" (combine the users into one commit author). It's the only way to guarantee that git will actually track the authors and rows correctly.
What do you mean here?
Signing it with a custom author that would represent the multiple authors? I do not know of anything beyond  `git commit --author=<author> `, is this what you mean (custom author on specific commits)?
